version: '3.1'
services:
    db:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db_data:/usr/data
        ports:
            - 3306:3306
    web:
        image: anwarendo/php:7.4
        # environment:
        #     - APACHE_RUN_USER=#${UID}
        #     - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 13000:80
        depends_on: 
            - db
        links:
            - db
    # adminer:
    #     image: adminer
    #     restart: unless-stopped
    #     ports:
    #         - 8080:8080
volumes:
    db_data:
    src:
